// <auto-generated />
namespace IQManClient.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lineupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lineupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201905190048533_lineupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
